#!/bin/bash

#Aceder ao diretório home
cd ~
#Criar um diretório para o miniconda
mkdir -p ~/miniconda3
#Obter miniconda
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
#Instalar miniconda
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
~/miniconda3/bin/conda init bash

