#!/bin/bash

#Aceder ao cornales_outfiles
cd ~/ipyrad-assembly/cornales_outfiles

#Descarregar ficheiro para executar o MrBayes.
wget https://raw.githubusercontent.com/Nunomcmm/analysys_of_biological_sequences/master/Assignment2_Anexos/MB_Cornales

#Fazer uma árvore ML utilizando o RAxML
raxmlHPC-PTHREADS-AVX -f a -s cornales.phy -m GTRGAMMA -x 2525 -p 2525 -N 100 -n Cornales_ML

#Fazer uma árvore de BI utilizando o MrBayes
mb cornales.nex cornales_mb
